version: 0.0
os: linux

files:
  - source: /
    destination: /home/root/server

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
  BeforeInstall:
    - location: scripts/server_clear.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 20
      runas: root
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 20
      runas: root
